version: '3'
volumes:
  db-store:
services:
  python3:
    build: .
    container_name: flask_apache_test
    hostname: flask_apache_test
    entrypoint: >
      /bin/sh -c "
      apachectl -D FOREGROUND
      "
    tty: true
    volumes:
      - ./app:/app
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 18080:80
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - 43306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    
    platform: linux/amd64
  